.PHONY: clean All

All:
	@echo "----------Building project:[ pc-segmentation - Debug ]----------"
	@"$(MAKE)" -f  "pc-segmentation.mk"
clean:
	@echo "----------Cleaning project:[ pc-segmentation - Debug ]----------"
	@"$(MAKE)" -f  "pc-segmentation.mk" clean
